[tool.black]
line-length = 100

[tool.codespell]
ignore-words-list = "fwe,te,als"
skip = "./.git,*.svg"

[tool.isort]
combine_as_imports = true
line_length = 100
profile = "black"
skip_gitignore = true
