[tool.black]
line-length = 100

[tool.codespell]
ignore-words-list = "fwe,softwares,te,connectivty,analyisis,alignement,publically,mininum,continous,als,inlcudes,exeprimental,directon"
skip = "./.git,*.svg"

[tool.isort]
combine_as_imports = true
line_length = 100
profile = "black"
skip_gitignore = true
